[pytest]
DJANGO_SETTINGS_MODULE = lsa_booking.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test* *Tests
python_functions = test_*
testpaths = bookings
addopts =
    --verbose
    --tb=short
    --cov=bookings
    --cov-report=html
    --cov-report=term-missing
    --cov-report=xml