# Generated by Django 4.2.7 on 2026-08-16 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'parents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'is_active'], name='parents_email_a9b17f_idx'), models.Index(fields=['city', 'state'], name='parents_city_2836f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='LSA_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('qualification', models.CharField(choices=[('high_school', 'High School Diploma'), ('associate', 'Associate Degree'), ('bachelor', 'Bachelor Degree'), ('master', 'Master Degree'), ('phd', 'PhD'), ('certification', 'Professional Certification')], db_index=True, max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('intermediate', 'Intermediate (2-5 years)'), ('senior', 'Senior (5-10 years)'), ('expert', 'Expert (10+ years)')], db_index=True, max_length=20)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('specialization', models.CharField(help_text='Area of specialization (e.g., ADHD, Autism, Dyslexia)', max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('is_willing_to_relocate', models.BooleanField(default=False)),
                ('skills', models.TextField(help_text="Comma-separated list of skills (e.g., 'ADHD,Autism,Sign Language')")),
                ('certifications', models.TextField(blank=True, help_text='Comma-separated list of certifications')),
                ('bio', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate in USD', max_digits=10)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_to', models.TimeField(blank=True, null=True)),
                ('available_days', models.CharField(default='Mon,Tue,Wed,Thu,Fri', help_text='Comma-separated days of availability', max_length=50)),
                ('background_check_completed', models.BooleanField(default=False)),
                ('background_check_date', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('profile_status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lsa_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'is_available'], name='lsa_profile_email_c74245_idx'), models.Index(fields=['city', 'state'], name='lsa_profile_city_4f30a1_idx'), models.Index(fields=['experience_level', 'qualification'], name='lsa_profile_experie_312216_idx'), models.Index(fields=['profile_status', 'verified'], name='lsa_profile_profile_40947b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('child_age', models.IntegerField()),
                ('child_grade', models.CharField(blank=True, max_length=50)),
                ('learning_needs', models.TextField(help_text="Description of child's learning needs")),
                ('session_type', models.CharField(choices=[('online', 'Online/Virtual'), ('in_person', 'In-Person'), ('hybrid', 'Hybrid')], default='online', max_length=20)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('location', models.CharField(blank=True, help_text='Location for in-person sessions', max_length=255)),
                ('subject', models.CharField(help_text='Subject or topic for the session', max_length=200)),
                ('goals', models.TextField(help_text='Learning goals for this session')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or requirements')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Payment Pending'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('payment_pending', 'Payment Pending'), ('payment_failed', 'Payment Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('lsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='bookings.lsa_profile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='bookings.parent')),
            ],
            options={
                'db_table': 'booking_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent', 'status'], name='booking_req_parent__a17524_idx'), models.Index(fields=['lsa', 'status'], name='booking_req_lsa_id_ee4296_idx'), models.Index(fields=['start_time', 'end_time'], name='booking_req_start_t_f1a550_idx'), models.Index(fields=['status', 'payment_status'], name='booking_req_status_2c5d91_idx')],
            },
        ),
    ]
